package org.apache.struts.action;

import org.springframework.http.HttpStatus;
import org.springframework.web.client.HttpStatusCodeException;

/**
 * Thrown when a token generated by the Cancel tag is found in the request, but
 * the cancellable property for the Action Mapping is not set.
 */
public class InvalidCancelException extends HttpStatusCodeException {

  public InvalidCancelException() {
    super(HttpStatus.BAD_REQUEST);
  }

  public InvalidCancelException(String message) {
    super(HttpStatus.BAD_REQUEST, message);
  }
}
