package org.apache.struts.action;

/**
 * Thrown when a token generated by the Cancel tag is found in the request, but
 * the cancellable property for the Action Mapping is not set.
 */
public class InvalidCancelException extends Exception {
  public InvalidCancelException() {
    super();
  }

  public InvalidCancelException(String message) {
    super(message);
  }
}
